### ISSUE TITLE
Fix strange docker and keycloak problems with direkt links

### ISSUE THREAD

**Issue by FRickReich** [Envoii-Technologies/proxy#3]
If a link is called, sometimes the upstream server fails on a redirect.

Example:

i click on "preview card" inside of the editor and get the following failed link:

http://host.docker.internal/auth/realms/acme/protocol/openid-connect/auth?client_id=envoii-client&redirect_uri=http%3A%2F%2Fhost.docker.internal%2Facme%2Fcards%2Fview%2F65d35d2d3e6b6b6844b95d6f&state=b58de4df-404b-4052-8ff4-fe0adab0da62&response_mode=fragment&response_type=code&scope=openid&nonce=0f68cf54-a6aa-4a80-9b46-753b4f707120

**Comment by saschaB91** [comment]
fixed in https://github.com/Envoii-Technologies/proxy/commit/b4b63cc210d2f416567d5b9112135b0e74929a15

**Comment by saschaB91** [comment]
fixed in https://github.com/Envoii-Technologies/proxy/commit/b4b63cc210d2f416567d5b9112135b0e74929a15
